module.exports = (function() {
	const Q_max = 4.176,
        Q_mid = 0.624,
        K_VP = 0.022,
        h_bar = 755,
        t_ot = -23,
        t_nar = -1.7,
        n = 191,
        Ko = 2203,
        Q_ki = [1.046, 1.774],
        b_ki = [155.71, 157.38],
        Q_rn = [8134, 8134],
        t_hp = [20, 19],
        alfa_dg = [1.3, 1.25],
        t_dg = [135, 180],
        t_k_vh = [60, 60],
        t_k_vih = [79, 98],
    	Q_gvp = Q_mid * 1.2 * 24 * n,
		Q_op = Q_max * Ko,
		Q_usful = Q_gvp + Q_op,
		Q_kot = Q_usful * (1 + K_VP),
		Q_kot_mid = Q_kot / (n * 24),
		Q_op_mid = Q_kot_mid - Q_mid * (1 + K_VP),
		Q_pl = Q_ki.reduce((a, b) => a + b);

	return {
		Q_max,
		Q_mid,
        Q_op_mid,
        Q_pl,
		h_bar,
		t_ot,
		t_nar,
		n,
		Ko,
        K_VP,
		Q_ki,
		b_ki,
		Q_rn,
		t_hp,
		alfa_dg,
		t_dg,
		t_k_vh,
		t_k_vih
	}
})();